# Generated by Django 5.0.3 on 2024-03-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogpost_chead0_alter_blogpost_chead1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='head0',
            new_name='fifth_head',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='chead0',
            new_name='fifth_head_content',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='head1',
            new_name='first_head',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='chead1',
            new_name='first_head_content',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='head2',
            new_name='fourth_head',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='chead2',
            new_name='fourth_head_content',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='second_head',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='second_head_content',
            field=models.TextField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='sixth_head',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='sixth_head_content',
            field=models.TextField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='third_head',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='third_head_content',
            field=models.TextField(default='', max_length=5000),
        ),
    ]
