# Generated by Django 5.0.3 on 2024-03-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_head0_blogpost_fifth_head_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='fifth_head',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='fifth_head_content',
            field=models.TextField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='fourth_head',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='fourth_head_content',
            field=models.TextField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='sixth_head',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='sixth_head_content',
            field=models.TextField(blank=True, default='', max_length=5000),
        ),
    ]
